; 練習問題 2.3 平面上の⻑方形の表現を実装
(load "sicp2.1.2_2.2.rkt")
(define (make-rect bottom-left top-right)
  (cons bottom-left top-right))
(define (bottom-left r)
  (car r))
(define (top-right r)
  (cdr r))
(define (bottom-right r)
  (make-point (x-point (top-right r))
                (y-point (bottom-left r))))
(define (top-left r)
  (make-point (x-point (bottom-left r))
                (y-point (top-right r))))
(define (width-rect r)
  (abs (- (x-point (bottom-left r))
           (x-point (top-right r)))))
(define (height-rect r)
  (abs (- (y-point (bottom-left r))
           (y-point (top-right r)))))
; ある⻑方形の外周の⻑さと面積を計算する手続きを書け。
(define (perimeter-rect r)
  (* 2.0 (+ (width-rect r) (height-rect r))))
(define (area-rect r)
  (* (width-rect r) (height-rect r)))
